name: GitHub Actions - Back Image Build
run-name: Back docker image building
env:
  REGISTRY: ghcr.io
on:
  push:
    branches:
      - trunk
    paths-ignore:
      - '.github/front-image-build.yaml'
      - 'kubernetes/**'
      - 'front/**'
jobs:
  Build-Back-DockerImage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: rm back/devenv.local.nix
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        env:
          DOCKER_BUILDKIT_SANDBOX_MODE: "disabled"
        with:
          context: "{{defaultContext}}:back"
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            NIX_INSTALLER_EXTRA_CONF=filter-syscalls = false
            NIX_INSTALL_FLAGS='--no-sandbox'
          tags: ${{ env.REGISTRY }}/${{ github.repository }}-back:${{ github.run_id }}