name: GitHub Actions - Back Image Build
run-name: Back docker image building
env:
  REGISTRY: ghcr.io
on:
  push:
    branches:
      - trunk
    paths-ignore:
      - '.github/front-image-build.yaml'
      - 'kubernetes/**'
      - 'front/**'
jobs:
  Build-DockerImage:
    runs-on: [self-hosted, Linux, X64, default]
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install devenv
        run: nix-env -iA devenv -f https://github.com/NixOS/nixpkgs/tarball/nixpkgs-unstable
      - name: Run CI
        run: cd back && devenv ci