name: GitHub Actions - Front Image Build
run-name: Front docker image building
env:
  REGISTRY: ghcr.io
on:
  push:
    branches:
      - trunk
    paths-ignore:
      - '.github/back-image-build.yaml'
      - 'kubernetes/**'
      - 'back/**'
jobs:
  Build-Front-DockerImage:
    runs-on: [self-hosted, Linux, X64, default]
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install devenv
        run: nix-env -iA devenv -f https://github.com/NixOS/nixpkgs/tarball/nixpkgs-unstable
      - name: Run CI
        run: cd front && devenv shell bun run build && devenv container copy prod
      - run: docker image ls